"""initial schema

Revision ID: 4579c6daf4d1
Revises: 
Create Date: 2026-09-05 19:54:31.148918

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4579c6daf4d1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('search_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region_query', sa.String(length=255), nullable=False),
    sa.Column('segment_query', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='searchrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_runs'))
    )
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='companystatus', native_enum=False, length=20), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_companies_category_id_categories')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_companies_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_canonical_name'), 'companies', ['canonical_name'], unique=False)
    op.create_table('audit_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('presence_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_snapshots_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_snapshots'))
    )
    op.create_index(op.f('ix_audit_snapshots_company_id'), 'audit_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_snapshots_run_id'), 'audit_snapshots', ['run_id'], unique=False)
    op.create_table('company_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=20), nullable=False),
    sa.Column('raw_reference', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_sources_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_sources')),
    sa.UniqueConstraint('source', 'external_id', name='uq_company_sources_source_external_id')
    )
    op.create_index(op.f('ix_company_sources_company_id'), 'company_sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sources_source'), 'company_sources', ['source'], unique=False)
    op.create_table('identity_merge_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('primary_company_id', sa.Uuid(), nullable=False),
    sa.Column('merged_company_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merged_company_id'], ['companies.id'], name=op.f('fk_identity_merge_logs_merged_company_id_companies')),
    sa.ForeignKeyConstraint(['primary_company_id'], ['companies.id'], name=op.f('fk_identity_merge_logs_primary_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_merge_logs'))
    )
    op.create_index(op.f('ix_identity_merge_logs_merged_company_id'), 'identity_merge_logs', ['merged_company_id'], unique=False)
    op.create_index(op.f('ix_identity_merge_logs_primary_company_id'), 'identity_merge_logs', ['primary_company_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('audit_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=True),
    sa.Column('state', sa.Enum('CONFIRMED', 'NOT_DETECTED', 'INCONCLUSIVE', 'INACCESSIBLE', 'NOT_CHECKED', 'STALE', name='datastate', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('method', sa.Enum('STRUCTURED_FIELD', 'HEURISTIC_MATCH', 'INFERENCE', 'MANUAL', name='evidencemethod', native_enum=False, length=30), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('raw_reference', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['audit_snapshot_id'], ['audit_snapshots.id'], name=op.f('fk_evidence_audit_snapshot_id_audit_snapshots')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_evidence_company_id_companies')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['evidence.id'], name=op.f('fk_evidence_superseded_by_id_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_audit_snapshot_id'), 'evidence', ['audit_snapshot_id'], unique=False)
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_evidence_field'), 'evidence', ['field'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='opportunitytier', native_enum=False, length=20), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('recommended_product', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_snapshot_id'], ['audit_snapshots.id'], name=op.f('fk_opportunity_scores_audit_snapshot_id_audit_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores'))
    )
    op.create_index(op.f('ix_opportunity_scores_audit_snapshot_id'), 'opportunity_scores', ['audit_snapshot_id'], unique=True)
    op.create_table('website_quality_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_snapshot_id'], ['audit_snapshots.id'], name=op.f('fk_website_quality_snapshots_audit_snapshot_id_audit_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_quality_snapshots'))
    )
    op.create_index(op.f('ix_website_quality_snapshots_audit_snapshot_id'), 'website_quality_snapshots', ['audit_snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_quality_snapshots_audit_snapshot_id'), table_name='website_quality_snapshots')
    op.drop_table('website_quality_snapshots')
    op.drop_index(op.f('ix_opportunity_scores_audit_snapshot_id'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_evidence_field'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_audit_snapshot_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_identity_merge_logs_primary_company_id'), table_name='identity_merge_logs')
    op.drop_index(op.f('ix_identity_merge_logs_merged_company_id'), table_name='identity_merge_logs')
    op.drop_table('identity_merge_logs')
    op.drop_index(op.f('ix_company_sources_source'), table_name='company_sources')
    op.drop_index(op.f('ix_company_sources_company_id'), table_name='company_sources')
    op.drop_table('company_sources')
    op.drop_index(op.f('ix_audit_snapshots_run_id'), table_name='audit_snapshots')
    op.drop_index(op.f('ix_audit_snapshots_company_id'), table_name='audit_snapshots')
    op.drop_table('audit_snapshots')
    op.drop_index(op.f('ix_companies_canonical_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('search_runs')
    op.drop_table('regions')
    op.drop_table('categories')
    # ### end Alembic commands ###
