"""discovery search run details and provider usage

Revision ID: 4309f578903d
Revises: 4579c6daf4d1
Create Date: 2026-09-05 20:26:35.990235

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4309f578903d'
down_revision: str | None = '4579c6daf4d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('fields_requested', sa.JSON(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], name=op.f('fk_provider_usage_records_search_run_id_search_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_usage_records'))
    )
    op.create_index(op.f('ix_provider_usage_records_search_run_id'), 'provider_usage_records', ['search_run_id'], unique=False)
    # `server_default` nas duas colunas NOT NULL novas é só para que um
    # `search_runs` pré-existente (com linhas da Fase 0) não quebre a
    # migration — removido logo em seguida, já que o modelo Python define o
    # valor na aplicação, não no banco.
    op.add_column(
        'search_runs',
        sa.Column('provider', sa.String(length=60), nullable=False, server_default='google_places'),
    )
    op.add_column(
        'search_runs',
        sa.Column('parameters', sa.JSON(), nullable=False, server_default='{}'),
    )
    op.add_column('search_runs', sa.Column('raw_result_count', sa.Integer(), nullable=True))
    op.add_column('search_runs', sa.Column('normalized_result_count', sa.Integer(), nullable=True))
    op.add_column('search_runs', sa.Column('persisted_count', sa.Integer(), nullable=True))
    op.add_column('search_runs', sa.Column('new_company_count', sa.Integer(), nullable=True))
    op.add_column('search_runs', sa.Column('pages_fetched', sa.Integer(), nullable=True))
    op.add_column('search_runs', sa.Column('error_code', sa.String(length=60), nullable=True))
    op.add_column('search_runs', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('search_runs', sa.Column('cost_currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('search_runs') as batch_op:
        # `status` só cresce de VARCHAR(20) para VARCHAR(24) para caber os
        # dois novos valores (`partially_completed`, `cancelled`) — ainda
        # não é um ENUM nativo do banco (ver docs/data-model.md). A
        # alteração de tipo exige "batch mode" para funcionar em SQLite.
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                'PENDING', 'RUNNING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED',
                name='searchrunstatus', native_enum=False, length=24,
            ),
            existing_nullable=False,
        )
        batch_op.alter_column('provider', server_default=None)
        batch_op.alter_column('parameters', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_runs') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(
                'PENDING', 'RUNNING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED',
                name='searchrunstatus', native_enum=False, length=24,
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
    op.drop_column('search_runs', 'cost_currency')
    op.drop_column('search_runs', 'error_message')
    op.drop_column('search_runs', 'error_code')
    op.drop_column('search_runs', 'pages_fetched')
    op.drop_column('search_runs', 'new_company_count')
    op.drop_column('search_runs', 'persisted_count')
    op.drop_column('search_runs', 'normalized_result_count')
    op.drop_column('search_runs', 'raw_result_count')
    op.drop_column('search_runs', 'parameters')
    op.drop_column('search_runs', 'provider')
    op.drop_index(op.f('ix_provider_usage_records_search_run_id'), table_name='provider_usage_records')
    op.drop_table('provider_usage_records')
    # ### end Alembic commands ###
