"""identity resolution dedup candidates and source coordinates

Revision ID: fdd00c2c28f6
Revises: 4309f578903d
Create Date: 2026-09-05 21:06:31.114909

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd00c2c28f6'
down_revision: str | None = '4309f578903d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('resulting_company_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.Enum('MATCH', 'NO_MATCH', 'INCONCLUSIVE', name='matchdecision', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('AUTO_RESOLVED', 'PENDING_REVIEW', 'CONFIRMED_SAME', 'CONFIRMED_DIFFERENT', name='dedupcandidatestatus', native_enum=False, length=24), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_dedup_candidates_company_id_companies')),
    sa.ForeignKeyConstraint(['resulting_company_id'], ['companies.id'], name=op.f('fk_dedup_candidates_resulting_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedup_candidates'))
    )
    op.create_index(op.f('ix_dedup_candidates_company_id'), 'dedup_candidates', ['company_id'], unique=False)
    op.create_index(op.f('ix_dedup_candidates_resulting_company_id'), 'dedup_candidates', ['resulting_company_id'], unique=False)
    op.add_column('company_sources', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('company_sources', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sources', 'longitude')
    op.drop_column('company_sources', 'latitude')
    op.drop_index(op.f('ix_dedup_candidates_resulting_company_id'), table_name='dedup_candidates')
    op.drop_index(op.f('ix_dedup_candidates_company_id'), table_name='dedup_candidates')
    op.drop_table('dedup_candidates')
    # ### end Alembic commands ###
