"""digital audit and website quality

Revision ID: 4a02ef8489da
Revises: fdd00c2c28f6
Create Date: 2026-09-05 21:50:58.589674

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a02ef8489da'
down_revision: str | None = 'fdd00c2c28f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_snapshots', sa.Column('website_url', sa.String(length=2048), nullable=True))
    op.add_column('audit_snapshots', sa.Column('site_state', sa.Enum('CONFIRMED', 'NOT_DETECTED', 'INCONCLUSIVE', 'INACCESSIBLE', 'NOT_CHECKED', 'STALE', name='datastate', native_enum=False, length=20), nullable=True))
    # `server_default` só para não quebrar um `audit_snapshots` pré-existente
    # com linhas da Fase 0 (nenhuma tinha `status` antes) — removido a
    # seguir, já que o modelo Python define o valor na aplicação.
    op.add_column(
        'audit_snapshots',
        sa.Column(
            'status',
            sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='auditstatus', native_enum=False, length=20),
            nullable=False,
            server_default='PENDING',
        ),
    )
    with op.batch_alter_table('audit_snapshots') as batch_op:
        batch_op.alter_column('status', server_default=None)
    op.add_column('audit_snapshots', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_snapshots', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_snapshots', sa.Column('error_code', sa.String(length=60), nullable=True))
    op.add_column('audit_snapshots', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('website_quality_snapshots', sa.Column('components', sa.JSON(), nullable=True))
    op.add_column('website_quality_snapshots', sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=20), nullable=True))
    op.add_column('website_quality_snapshots', sa.Column('limitations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_quality_snapshots', 'limitations')
    op.drop_column('website_quality_snapshots', 'confidence')
    op.drop_column('website_quality_snapshots', 'components')
    op.drop_column('audit_snapshots', 'error_message')
    op.drop_column('audit_snapshots', 'error_code')
    op.drop_column('audit_snapshots', 'finished_at')
    op.drop_column('audit_snapshots', 'started_at')
    op.drop_column('audit_snapshots', 'status')
    op.drop_column('audit_snapshots', 'site_state')
    op.drop_column('audit_snapshots', 'website_url')
    # ### end Alembic commands ###
