"""opportunity scoring and sales brief

Revision ID: 36de4260089f
Revises: 4a02ef8489da
Create Date: 2026-09-06 06:28:32.693464

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36de4260089f'
down_revision: str | None = '4a02ef8489da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_briefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_score_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='salesbriefstatus', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sales_briefs_company_id_companies')),
    sa.ForeignKeyConstraint(['opportunity_score_id'], ['opportunity_scores.id'], name=op.f('fk_sales_briefs_opportunity_score_id_opportunity_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_briefs'))
    )
    op.create_index(op.f('ix_sales_briefs_company_id'), 'sales_briefs', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_briefs_opportunity_score_id'), 'sales_briefs', ['opportunity_score_id'], unique=False)
    op.add_column('opportunity_scores', sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=20), nullable=True))
    # `server_default` só para não quebrar uma linha pré-existente de
    # `opportunity_scores` (nenhuma tinha `scoring_version`/`updated_at`
    # antes) — removido a seguir, já que o modelo Python define o valor na
    # aplicação. Mesmo padrão de 0004_digital_audit.py para `status`.
    op.add_column(
        'opportunity_scores',
        sa.Column('scoring_version', sa.String(length=10), nullable=False, server_default='v1'),
    )
    op.add_column(
        'opportunity_scores',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    with op.batch_alter_table('opportunity_scores') as batch_op:
        batch_op.alter_column('scoring_version', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_scores', 'updated_at')
    op.drop_column('opportunity_scores', 'scoring_version')
    op.drop_column('opportunity_scores', 'confidence')
    op.drop_index(op.f('ix_sales_briefs_opportunity_score_id'), table_name='sales_briefs')
    op.drop_index(op.f('ix_sales_briefs_company_id'), table_name='sales_briefs')
    op.drop_table('sales_briefs')
    # ### end Alembic commands ###
